### ISSUE TITLE
proxyReqOptDecorator documentation example is wrong

### ISSUE THREAD

**Issue by fkrauthan** [nsimmons/koa-better-http-proxy#14]
The Documentation for `proxyReqOptDecorator` states that you can use to rewrite the target path. But this is wrong as the `proxyReqPathResolver` is called AFTER `proxyReqOptDecorator` and by default overwrites the path that was set within the `proxyReqOptDecorator`. I think either the order of the two lifecycles should be switched or the documentation example should be adjusted to not state that you can change the path as part of that lifecycle.

**Comment by bolein** [comment]
+1

**Comment by hfuuss** [comment]
+1
