### ISSUE TITLE
How to set up multiple host names

### ISSUE THREAD

**Issue by henryoliver** [nsimmons/koa-better-http-proxy#2]
Hi, I don't know if it is right to use Koajs as a reverse proxy but my goal is to proxy different external URLs(hosts) to different ports on my server. Could you provide one example?

How can I pass a table of hosts with their forward ports instead of just one host as the example below:
`app.use(proxy('www.google.com'));`

Thank you!

**Comment by stoneChen** [comment]
You can use `proxyReqOptDecorator` to dynamically modify the field `host` every request.
Just like this:
```js
// the '0' is to avoid null asset
 koaHttpProxy('0', {
      async proxyReqOptDecorator(proxyReqOpts, ctx) {
        // you should handle the _proxyTarget yourself
        const parsedTarget = urlUtils.parse(ctx._proxyTarget, true)
        proxyReqOpts.host = parsedTarget.hostname
        proxyReqOpts.port = parsedTarget.port
        proxyReqOpts.https = parsedTarget.protocol === 'https:'

        return  proxyReqOpts
      }
)
```

**Comment by nsimmons** [comment]
@stoneChen suggestion above will do the trick if KoaJS makes sense in your specific case.

But if you were looking to use KoaJS as a reverse proxy and nothing else, I would recommend looking into something like Nginx instead(https://www.nginx.com/resources/admin-guide/reverse-proxy/). To get comparable functionality to what Nginx (and HAProxy, etc) offers as a reverse proxy will require a bunch of logic on top of this middleware.

**Comment by henryoliver** [comment]
Thank you, guys! Start to use Nginx with NodeJS and work perfectly!

**Comment by stoneChen** [comment]
Yes my previous suggestion is a little tricky，recently I find that the `host` can also be a function(see https://github.com/nsimmons/koa-better-http-proxy/blob/master/lib/requestOptions.js#L26) , which is not mentioned in the documents.
So we can dynamically set the proxy target for every request!

**Comment by alexeyr-c** [comment]
@nsimmons Would it be possible to update the types/documentation to include host-as-function from https://github.com/nsimmons/koa-better-http-proxy/issues/2#issuecomment-334653168? I'll happily make a PR for it if you want.
