### ISSUE TITLE
Proxy returns wrong response on high traffic

### ISSUE THREAD

**Issue by junereycasuga** [nsimmons/koa-better-http-proxy#21]
We are using `koa-better-http-proxy` to proxy another API for getting a user data. We have already checked that we were sending the correct request headers in every request. But at some point, there are few responses that the email data from the response and the email from our session didn't match like the logs below:

```
LOG: proxyReqOptDecorator { 
    transactionId: '0a8f92ca-5b77-4e8f-b3c0-03c079c05bde',
    emailFromSession: 'qatest30@mail.com' 
}
LOG: proxyReqOptDecorator { 
    transactionId: '59cb6a30-d6d3-4475-a941-d0d655b369e7',
    emailFromSession: 'qatest31@mail.com' 
}
LOG: userResDecorator { 
    transactionId: '0a8f92ca-5b77-4e8f-b3c0-03c079c05bde',
    emailFromResponse: 'qatest31@mail.com' 
}
LOG: userResDecorator { 
    transactionId: '59cb6a30-d6d3-4475-a941-d0d655b369e7',
    emailFromResponse: 'qatest31@mail.com' 
}
```

We have already asked the developers of the API we are proxying about it and they have told us that they haven't received requests in these cases. So we're wondering how we are still able to get data as a response.

Our dependencies are:
```
"koa": "^2.5.0",
"koa-better-http-proxy": "^0.2.4"
```

**Comment by samundra** [comment]
Hi guys, is there any update on it? So, a possible way to debug this issue?

**Comment by junereycasuga** [comment]
i'm not expecting any answer on this anymore 🤷🏽‍♂️
